### ISSUE TITLE
[Idea] Small redesign

### ISSUE THREAD

**Issue by dav1312** [daylen/stockfish-web#3]
- Changing the colors
- Adding "Stockfish" next to the logo
- Centering the text in the subfooter
- Custom scrollbar

![New](https://user-images.githubusercontent.com/63931154/139415385-8c923176-4de6-40f7-84e3-7c8e2826f229.png)

- Width 100%
- Alternate colors in tables
- Vertically center the text in tables
- Move download buttons to the end

![New2](https://user-images.githubusercontent.com/63931154/139415394-c7c8e6c3-89f4-4448-bd0b-68ed273a2203.png)

**Comment by vondele** [comment]
Maybe you can propose the changes as a PR? It might be easier for Daylen to comment on it. I guess the largest change visually is the change of color, but it is an option according to me.

**Comment by 1MadCat1** [comment]
Hi, just want to know about the Logo it self
Am I able to use it is the intro to my game?
